### ISSUE TITLE
Create a quick conversion binary

### ISSUE THREAD

**Issue by caged** [benbalter/vangogh#2]
@benbalter this is rad!  I'd like to make a feature request!  Often I end up with CSV files that contain a variety of numbers.  What I'd like to do is just point something at that csv file and have it print an anonymized version of it to STDOUT that I can pipe into a file.  It would beat having to convert numbers one by one or even having to write ruby when you just want a quick conversion.

Think:

```
./bin/vangogh --in my/details/data.csv --anonymize total,total_pushes > converted.csv
```

**Comment by benbalter** [comment]
Done over in #3.

```
$ vangogh abstract csv.csv >> output.csv
```

and 

```
$ vangogh abstract csv.csv --fields foo bar >> output.csv
```

Should work as describe above. :smile:

**Comment by caged** [comment]
:sparkles:
